FROM python:3.8-slim-buster

ENV LISTEN_PORT=5000
EXPOSE 5000

WORKDIR /app

COPY requirements.txt requirements.txt
ADD . /app

RUN pip3 install -r requirements.txt

COPY . . 

CMD ["python3", "app.py"]